name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./simple-api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest

      - name: Build and push database
        uses: docker/build-push-action@v6
        with:
          context: ./database
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest

      - name: Build and push httpd
        uses: docker/build-push-action@v6
        with:
          context: ./http-server
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
